import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Product1 from '@/components/Product1'
import Product2 from '@/components/Product2'
import Parallax1 from '@/components/Parallax1'
import Merch from '@/components/Merch'
import Newsletter from '@/components/Newsletter'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Header />
        <Product1 />
        <Product2 />
        <Parallax1 />
        <Merch />
        <Newsletter />
        <Footer />
      </main>
    </>
  )
}
